// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmg1IOE8i64QqMLt1S5tTYayCTxAR0Qy8',
    appId: '1:750164179815:web:ecc668fb1d211e5aee0dc2',
    messagingSenderId: '750164179815',
    projectId: 'todoapp-b26f0',
    authDomain: 'todoapp-b26f0.firebaseapp.com',
    storageBucket: 'todoapp-b26f0.appspot.com',
    measurementId: 'G-TL5P3WM71Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNSYM9dqWrG6bX8NDKNd_1Kwd7KHbn80',
    appId: '1:750164179815:android:f56b3f38f1e98b3eee0dc2',
    messagingSenderId: '750164179815',
    projectId: 'todoapp-b26f0',
    storageBucket: 'todoapp-b26f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgsYDNmMmiJlvgR2ZFWYS4I-d3Jcspzw4',
    appId: '1:750164179815:ios:645c6fa8c77ff491ee0dc2',
    messagingSenderId: '750164179815',
    projectId: 'todoapp-b26f0',
    storageBucket: 'todoapp-b26f0.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgsYDNmMmiJlvgR2ZFWYS4I-d3Jcspzw4',
    appId: '1:750164179815:ios:645c6fa8c77ff491ee0dc2',
    messagingSenderId: '750164179815',
    projectId: 'todoapp-b26f0',
    storageBucket: 'todoapp-b26f0.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmg1IOE8i64QqMLt1S5tTYayCTxAR0Qy8',
    appId: '1:750164179815:web:7568c4745bc385fbee0dc2',
    messagingSenderId: '750164179815',
    projectId: 'todoapp-b26f0',
    authDomain: 'todoapp-b26f0.firebaseapp.com',
    storageBucket: 'todoapp-b26f0.appspot.com',
    measurementId: 'G-0ZPW6P0FDV',
  );
}
